<?php
require_once __DIR__ . '/config.php';

function ce_auth_configured() {
    return file_exists(AUTH_FILE);
}

function ce_get_password_hash() {
    if (!ce_auth_configured()) return null;
    $data = include AUTH_FILE;
    return is_array($data) && !empty($data['hash']) ? $data['hash'] : null;
}

function ce_save_password_hash($hash) {
    if (!is_dir(DATA_DIR)) {
        mkdir(DATA_DIR, 0755, true);
    }
    // .htaccess belt-and-braces: this dir is never meant to be served directly.
    $htaccess = DATA_DIR . '/.htaccess';
    if (!file_exists($htaccess)) {
        file_put_contents($htaccess, "Require all denied\nDeny from all\n");
    }
    $php = "<?php\n// Auto-generated by admin/setup.php — do not edit by hand.\nreturn " . var_export(['hash' => $hash, 'updatedAt' => date('c')], true) . ";\n";
    $tmp = AUTH_FILE . '.tmp';
    file_put_contents($tmp, $php, LOCK_EX);
    rename($tmp, AUTH_FILE);
}

function ce_is_logged_in() {
    return !empty($_SESSION['ceylon_admin_authed']);
}

function ce_require_login($redirectTo = 'login.php') {
    if (!ce_auth_configured()) {
        header('Location: setup.php');
        exit;
    }
    if (!ce_is_logged_in()) {
        header('Location: ' . $redirectTo);
        exit;
    }
}

function ce_login_locked_out() {
    $a = $_SESSION['login_attempts'] ?? 0;
    $t = $_SESSION['login_locked_until'] ?? 0;
    return $a >= MAX_LOGIN_ATTEMPTS && time() < $t;
}

function ce_register_failed_login() {
    $_SESSION['login_attempts'] = ($_SESSION['login_attempts'] ?? 0) + 1;
    if ($_SESSION['login_attempts'] >= MAX_LOGIN_ATTEMPTS) {
        $_SESSION['login_locked_until'] = time() + LOGIN_LOCKOUT_SECONDS;
    }
}

function ce_clear_login_attempts() {
    unset($_SESSION['login_attempts'], $_SESSION['login_locked_until']);
}