<?php
// Auto-generated by admin/setup.php — do not edit by hand.
return array (
  'hash' => '$2y$12$cnUQZUuGwST52hfFPfGLTerXj9KrvgRTC6tBvmK23D09/5S2IP7BC',
  'updatedAt' => '2026-08-30T16:41:32+00:00',
);
