<?php
// Auto-generated by admin/setup.php — do not edit by hand.
return array (
  'hash' => '$2y$12$INHovSiOjjf/sMIqA0yfC.Zdr6DvJamlzwNVhq/hk8UiNzlSfkv/.',
  'updatedAt' => '2026-08-11T03:57:54+00:00',
);
